version: '2.4'

services:
  mysql_container:
    image: mysql:8.0.34
    restart: unless-stopped
    container_name: mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'tests'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_ROOT_PASSWORD: 'dev'

  mongo:
    image: mongo:6.0.9
    restart: unless-stopped
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
