version: '2.4'

services:
  chat_api:
    container_name: chat-api
    restart: unless-stopped
    build:
      context: .
      args:
        PORT: ${PORT}
    networks:
      - app-network
    environment:
      PORT: ${PORT}
      SECRET: ${SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URL: ${MONGODB_URL}
    env_file:
      - .env

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    ports:
      - '80:80'
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --standalone --preferred-challenges=http --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    env_file:
      - .env

  nginx:
    container_name: nginx
    depends_on:
      certbot:
        condition: service_completed_successfully
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

    networks:
      - app-network
    environment:
      PORT: ${PORT}
      DOMAIN: ${DOMAIN}
    env_file:
      - .env

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
